name: Rust Auto Format

permissions:
  contents: write

on:
  push:
    branches: [ develop ]
#  # Deactivated pending further investigation into #36.
#  pull_request:
#    branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # github.ref is useless on pull requests.
        # github.head_ref only exists on pull requests.
        ref: ${{ github.head_ref || github.ref }}

    - uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: nightly
        profile: minimal
        components: rustfmt
    - run: cat CI.toml >> Cargo.toml
    - run: cargo +nightly fmt --all

    - uses: stefanzweifel/git-auto-commit-action@v5.0.0
      with:
        commit_message: Automatic formatting commit (cargo +nightly fmt)
        file_pattern: '**/*.rs'
        commit_author: Rust Format Action <rust-format-action@schichler.dev>
